### ISSUE TITLE
latest year in time series

### ISSUE THREAD

**Issue by jason-lange** [palewire/cpi#38]
Hi,
I've ran cpi.update() before applying the CPI function to a quarterly time series and it appeared to work. But oddly there is a gap between my nominal numbers and those adjusted for the CPI change. How can I see what month and/or year is being used by default to adjust figures? If by default I'm using the 2018 CPI index, shouldn't my 2018 nominal and adjusted numbers be the same?
Thanks,
Jason
This is the code I used: 
cpi.update()
qcew['cpi_total_qtrly_wages'] = qcew.apply(lambda x: cpi.inflate(x.total_qtrly_wages, x.int_year) , axis=1)

**Comment by palewire** [comment]
I think we had a bug in `.update()` that has since been fixed. If you are still having the bug please let me know.
