### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by quancore** [palewire/cpi#44]
Currently BLS website is unavailable like this:
![Screenshot from 2020-08-08 17-47-17](https://user-images.githubusercontent.com/15036825/89714478-5b1ee400-d99f-11ea-9368-081357c74f86.png)

The library just parsing the error HTML page and there is no validation check whether the correct thing gets parsed from the website. Therefore, the importing of library is not working at all. Please add validation of parsed HTML page and a workaround for these kinds of problems (or give meaningful error messages on import).

**Comment by palewire** [comment]
The sqlite database is now included in the pypi file that ships, which I hope addresses this.
