### ISSUE TITLE
Project seems dead, alternatives?

### ISSUE THREAD

**Issue by t89** [palewire/cpi#57]
This project hasn't been updated in a long time, the data is incomplete and the inclusion of other currencies would be awesome. Does anybody know an alternative?

**Comment by palewire** [comment]
I'm working to ship an update today. Stand by.

**Comment by palewire** [comment]
New version is out. Give it a try https://pypi.org/project/cpi/0.1.17/#history

**Comment by t89** [comment]
Would you be so kind, to also push the code to this repo, please?

**Comment by palewire** [comment]
That's done.
