### ISSUE TITLE
cpi.update() not updating in jupyter notebook

### ISSUE THREAD

**Issue by vnessamartinez** [palewire/cpi#63]
The website has up to October it seems (https://www.bls.gov/data/inflation_calculator.htm) but the library only has up to August. Running `cpi.update()` in the notebook doesn't seem to pull anything.

**Comment by vnessamartinez** [comment]
https://data.bls.gov/timeseries/CUUR0000SA0

**Comment by palewire** [comment]
Thanks for the bug report. I'll take a look shortly.

**Comment by palewire** [comment]
I've release version 1.0.13 with the latest data. Give that a try.

**Comment by zia240637** [comment]
cpi.update() still persist. Getting one month old data bls.gov has published the value until November-22, whereas even after cpi.update() data is only until Oct-22.
<img width="271" alt="image" src="https://user-images.githubusercontent.com/23521529/210276231-587752e9-ae5d-454f-b82e-fb92661c18cc.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/23521529/210276349-4fb7ae8e-4618-4b01-bcef-f21de663e674.png">

**Comment by ShuaHousetable** [comment]
For me,the package isn't able to convert anything from 2022 for me.
Running cpi.update() doesn't seem to be helping/doing anything at all either.

**Comment by palewire** [comment]
@ShuaHousetable, what code snippet is leading to your error?

**Comment by ShuaHousetable** [comment]
@palewire for example, something as simple as:

val = cpi.inflate(1000, 2022)

Gives me:

CPIObjectDoesNotExist: Index of annual type for 2022-01-01 does not exist

**Comment by palewire** [comment]
Is there an annual valuable available for 2022 from BLS yet?

**Comment by palewire** [comment]
I have attempted to fix this bug in the new version released today. When you run `update` it now deletes the existing sqlite database and rebuilds it with a fresh data download. I'm hoping this will address the core issue. I'd appreciate if you'd give it a try.
