### ISSUE TITLE
Error in cpi.update()

### ISSUE THREAD

**Issue by tusharsinghsoam** [palewire/cpi#74]
Following is the traceback for the issue I faced during cpi.update():

Version of cpi used: 1.0.17

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In [40], line 1
----> 1 cpi.update()

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\cpi\__init__.py:163, in update()
    157 def update():
    158     """
    159     Updates the Consumer Price Index dataset at the core of this library.
    160 
    161     Requires an Internet connection.
    162     """
--> 163     Downloader().update()

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\cpi\download.py:75, in Downloader.update(self)
     73 # Download the TSVs
     74 logger.debug(f"Downloading {len(self.FILE_LIST)} files from the BLS")
---> 75 [self.get_tsv(file) for file in self.FILE_LIST]
     77 # Insert the TSVs
     78 logger.debug("Loading data into SQLite database")

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\cpi\download.py:75, in <listcomp>(.0)
     73 # Download the TSVs
     74 logger.debug(f"Downloading {len(self.FILE_LIST)} files from the BLS")
---> 75 [self.get_tsv(file) for file in self.FILE_LIST]
     77 # Insert the TSVs
     78 logger.debug("Loading data into SQLite database")

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\cpi\download.py:109, in Downloader.get_tsv(self, file)
    107 tsv_path = self.get_data_dir() / f"{file}.tsv"
    108 response = requests.get(url)
--> 109 assert response.ok
    110 with open(tsv_path, "w") as fp:
    111     fp.write(response.text)

AssertionError:

**Comment by palewire** [comment]
Hmm. If that response isn't "ok" I'm guessing something failed in the download, yes? Is it possible your internet went out? does this problem consistently persist? If so, maybe the BLS changed the URL we are downloading from?

**Comment by palewire** [comment]
I've attempted to patch this bug, and better test for its future recurrence. Please upgrade to version 1.0.18 and try again. Assuming it's fixed, I'll close this ticket. If you still have the problem, please speak up.

**Comment by tusharsinghsoam** [comment]
Hi Ben,

It has fixed the issue. I am able to run "cpi.update()" with the latest version (1.0.18). Thank you so much.

**Comment by palewire** [comment]
That's great news. I'm glad to hear it.
