### ISSUE TITLE
`cpi.update()` fail to request file from bls

### ISSUE THREAD

**Issue by fischcheng** [palewire/cpi#96]
`cpi.update` always returned assertion error in the function `get_tsv`

I went to the `download.py` and try to test the codes locally still failing.

I am suspecting the BLS is blocking kind of crawler/agent download, and randomly select agents from the `get_user_agent` method might not be working as expected?

Thank you!

**Comment by palewire** [comment]
Yes, I am having this same issue. I have filed a support ticket with BLS asking if they can help us remedy the problem. If we don't hear anything, we may need to re-engineer how we request the data.

**Comment by palewire** [comment]
Here's the response I got from the BLS:

> Hello Ben,
> 
> Per our [usage policy](https://www.bls.gov/bls/pss.htm), simply set the user-agent to your email address and your script should work fine. 
> 
> Depending on the programming language that you are using the syntax of adding your email address to the user-agent will be different. 
> 
> Additional samples of user-agent policy are available at https://meta.wikimedia.org/wiki/User-Agent_policy

**Comment by palewire** [comment]
This is fixed in version 1.1.0 which is shipping out now. You should be able to install an upgrade and try again in a couple minutes.

**Comment by fischcheng** [comment]
Thanks for the prompt reply and fix! confirmed fixed for me.

**Comment by palewire** [comment]
Great to hear.
